server:
  port:8080
spring:
  datasource:
    url: jdbc:mysql://root:REQUaUwRkdYmHILzMTJElipGkRFLiStV@metro.proxy.rlwy.net:12308/railway
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: REQUaUwRkdYmHILzMTJElipGkRFLiStV
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: levansy25012003@gmail.com
    password: hbak zebj leuw izxx
    protocol: smtp
    isSSL: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  expiration: 25920000
  secretKey: O4394zGjSD+N89CCcmec69mHTP206UonQ/09W6JZKrk=
twilio:
  accountSid: AC13d36731131a743fc854aa9fa1015bd2
  authToken: fcfbf301d4ac709b45689f38521301df
  serviceSid: VAa246151dad02892c4932ddb973c3c387

vnpay:
  tmnCode: D47VBXB3
  hashSecret: U427Z40R8RJP6KBPVVKADRRJVIX12NFQ
  returnUrl: http://localhost:8080/payment/vnpay-return
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  bankCode: NCB
  version: 2.1.0
  command: pay
  orderType: other
  client: http://localhost:5173/thanh-toan/
